# Generated by Django 5.2.17 on 2026-08-31 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField(help_text='Calories (kcal)', validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.PositiveIntegerField(help_text='Protein (grams)', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.PositiveIntegerField(default=0, help_text='Carbohydrates (grams)', validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.PositiveIntegerField(default=0, help_text='Fat (grams)', validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.PositiveIntegerField(default=0, help_text='Fiber (grams)', validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.PositiveIntegerField(default=0, help_text='Sugar (grams)', validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.PositiveIntegerField(default=0, help_text='Sodium (mg)', validators=[django.core.validators.MinValueValidator(0)])),
                ('water', models.PositiveIntegerField(default=0, help_text='Water (ml)', validators=[django.core.validators.MinValueValidator(0)])),
                ('caffeine', models.PositiveIntegerField(default=0, help_text='Caffeine (mg)', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='What you ate / workouts / comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
