# Generated by Django 5.2.17 on 2026-08-31 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutritionentry',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0, help_text='Calories burned (kcal)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
